### ISSUE TITLE
Razer Blade Stealth (QHD) doesn't work after daemon update

### ISSUE THREAD

**Issue by SammDu** [lah7/polychromatic#112]
After installing the latest upgrade from PPA, the applet couldn't show up, and controls are missing in the controller, with debug info here:   
[https://gist.github.com/SammDu/524c1a209602d78a07d47f2621c6542b](https://gist.github.com/SammDu/524c1a209602d78a07d47f2621c6542b)

The controller has similar debug info spitted out, even though it does start up; The applet doesn't show up altogether.
Looks to me like GTK changed their syntax up a bit while u stuck with the older version.
Please take a look, THANKS!!!

**Comment by lah7** [comment]
Few questions:

* What distro and desktop environment are you using?
* What version of GTK does it use?     On Ubuntu/Debian, run this:

      dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'

* Do you have a stacktrace / verbose output of the Controller too?

The root issue is probably because the Razer Blade Stealth recently added support for toggling the logo on the back (https://github.com/lah7/polychromatic/issues/104#issuecomment-318910090), but the daemon has been causing an exception due to missing implementations and as a result, the front-ends will take a hit... in this case, the tray applet doesn't even finish building the menu.

I flagged the issue to @terrycain (driver/daemon guy) but in the meantime I can prevent exceptions so the tray applet continues to build.

**Comment by terrycain** [comment]
^^ That should be fixed right?

**Comment by lah7** [comment]
The only difference here is that this is a `Razer Blade Stealth (QHD)` and the other in #104 was a `Razer Blade Stealth (Late 2016)` :confused:

**Comment by SammDu** [comment]
I'm on Ubuntu 17.04 Zesty Kernel 4.10.0-28-lowlatency, x64 architecture with Razer Blade late 2016

>  ~$ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64             3.22.11-0ubuntu3  amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                 3.22.11-0ubuntu3  amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common              3.22.11-0ubuntu3  all          common files for the GTK+ graphical user interface library
ii  libgtk2-perl                 2:1.2499-1        amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2.0-0:amd64            2.24.31-1ubuntu1  amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                2.24.31-1ubuntu1  amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-common             2.24.31-1ubuntu1  all          common files for the GTK+ graphical user interface library

Output of controller:   
[https://gist.github.com/SammDu/3b8e9420524b86d127e8747a55ca0899](https://gist.github.com/SammDu/3b8e9420524b86d127e8747a55ca0899)

So apparently it also falsely detected my device...it's a standard blade late 2016 version but showing stealth in the debug info

**Comment by hamad-abdy** [comment]
Same problem here after fresh install.
polychromatic-tray-applet also crashes.
Screenshot of polychromatic-controller is attached.


![screenshot from 2017-08-03 20-59-42](https://user-images.githubusercontent.com/30699486/28932461-c47f6e8a-788e-11e7-9fc8-fa3774b8d881.png)

**Comment by shapacko** [comment]
Same here, is there a way to revert to previous version?

**Comment by lah7** [comment]
You can roll back the daemon to [v1.14](https://github.com/terrycain/razer-drivers/releases/tag/v1.1.14) before the daemon added some code to toggle the logo... but we should fix the issue at hand.

So, the problem seems to be `Razer Blade Stealth (QHD)` has **all** of its options missing, except for this brightness toggle as seen in the screenshot?

Do try the [latest development build](https://github.com/lah7/polychromatic#daily-builds) of Polychromatic, some exceptions are being catched so the Controller/Tray applet  *should* continue running even when an error occurs while populating the page.

* Does that logo toggle work? (Supposedly this should light the Razer logo on the lid)
* If you try the latest version of Polychromatic, does anything improve?
* If you run it in a terminal, does it output any exceptions/stacktraces?

**Comment by hamad-abdy** [comment]
Using the **latest development build** and **without rolling back the daemon**:
Nothing changed in polychromatic-controller. It still detects my `Razer Blade` as `Razer Blade Stealth (QHD)`.
I noticed that it shows a warning saying `There was a problem communication with the daemon for this device` at the bottom of window at start-up (also checked in stable release, it shows the same warning).
Nothing works in polychromatic-controller: not logo toggle nor switching the brightness.
This time polychromatic-tray-applet runs, but it also detects my `Razer Blade` as `Razer Blade Stealth (QHD)`.
Fortunately keyboard backlight effects and its brightness could be changed using tray applet, but toggling logo does not work.

Output of `polychromatic-controller`:
```
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 1586, in update_device_active_options
    if self.active_device.fx.misc.logo.active == 1:
  File "/usr/lib/python3/dist-packages/razer/client/fx.py", line 632, in active
    return func()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLogoActive is not a valid method of interface razer.device.lighting.logo


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 184, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 472, in page_loaded
    page_bindings[self.current_page](self)
  File "/usr/bin/polychromatic-controller", line 2139, in menu
    appobj.update_device_active_options()
  File "/usr/bin/polychromatic-controller", line 1591, in update_device_active_options
    self.print_error(str(e), _("There was a problem communicating with the daemon for this device."))
  File "/usr/bin/polychromatic-controller", line 1166, in print_error
    dbg.stdout(human_text, self.error, 0)
AttributeError: 'Controller' object has no attribute 'error'
```

Output of `polychromatic-tray-applet`:
```
Skipping lighting_logo_active due to exception:
org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLogoActive is not a valid method of interface razer.device.lighting.logo


(polychromatic-tray-applet:9849): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by hamad-abdy** [comment]
I'm on Ubuntu Gnome 17.04, kernel: 4.10.0-30-generic, x64 architecture with Razer Blade late 2016.
```
:~$ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64             3.22.11-0ubuntu3  amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                 3.22.11-0ubuntu3  amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common              3.22.11-0ubuntu3  all          common files for the GTK+ graphical user interface library
ii  libgtk2-perl                 2:1.2499-1        amd64        Perl interface to the 2.x series of the Gimp Toolkit library
ii  libgtk2.0-0:amd64            2.24.31-1ubuntu1  amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                2.24.31-1ubuntu1  amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-cil                2.12.40-1         amd64        CLI binding for the GTK+ toolkit 2.12
ii  libgtk2.0-common             2.24.31-1ubuntu1  all          common files for the GTK+ graphical user interface library
```

**Comment by lah7** [comment]
Thanks for investigating -- so this device mix-up might be why things are throwing exceptions (but I can use these tracebacks to prevent this from causing the app to stop working properly). It's an issue at daemon level, as Polychromatic just asks and tells it to do things, like what device is plugged in, but this is getting the wrong info.

@terrycain (driver/daemon maintainer) can take a look if you [raise a new issue about this](https://github.com/terrycain/razer-drivers) and provide a fresh log as well as the USB PID.

    rm ~/.local/share/openrazer/logs/razer.log
    razer-daemon -r

^^ Will output a clean log, and also `lsusb | grep Razer` will list your device USB PID.

**Comment by lah7** [comment]
This commit partly addresses the logo toggle issue: https://github.com/terrycain/razer-drivers/commit/3580e58904be272bb90be5803dbb49e1e4946129 -- so the exceptions have stopped but the logo toggle is now missing as a result (#104)

**Comment by SammDu** [comment]
@lah7 But [RazerCommander](https://github.com/GabMus/razerCommander) seems to work fine...I tried installing that *after* this has happened and at least I get to set my keyboard to glow in static white (other modes work fine as well...except ripple and that's a known issue)   
so I don't think that the driver is the issue here...

**Comment by lah7** [comment]
razerCommander doesn't support logo/scroll wheel LED features for a device, so it would never have got the exception.

`dbus.exceptions.UnknownMethodException` was a daemon issue and has been fixed. This was because the feature request in https://github.com/lah7/polychromatic/issues/104#issuecomment-315563397 (add a toggle for the `logo` on the lid) caused issues for other Razer Blade's as Polychromatic tried to determine the logo's state but the daemon was throwing an exception, causing the rest of the application to give up as there were no checks.

As far as I can see, things should work fine now in the next daemon update. If you want it sooner, you can use [daemon's daily PPA (if running Ubuntu)](https://github.com/lah7/polychromatic/issues/105#issuecomment-315974801).

------
As for why your device is coming up as  `QHD` instead of `Late 2016`, I don't know. Please could you post the USB PID of your device?

    lsusb | grep Razer

**Comment by SammDu** [comment]
K I'll wait for that... USB PID:
`Bus 001 Device 007: ID 1532:020f Razer USA, Ltd`

**Comment by lah7** [comment]
That's technically correct then, the **Razer Blade Stealth (QHD)** is a `020f` device. You'll need to raise an issue against the daemon if you believe this is wrong.

Unless.... your Late 2016 model uses the same keyboard found in the QHD model.
