### ISSUE TITLE
WebKit dependency problem in Linux Mint 17.3

### ISSUE THREAD

**Issue by innoce9t** [lah7/polychromatic#16]
Hi,
I am trying to install the polychromatic on linux mint 17.3 ,cinnamon 64-bit. I downloaded the debian file and tried running it . I got the Error: Dependency is not satisfiable: gir1.2-webkit2-4.0
I searched for the webkit but i cannot find a way to install it. 

I am new to linux. Please guide me through this problem. 

P.S : Also i tried downloading the polychromatic using the manual method, I managed to have it installed and shows up in the applications however it does not run if i click on it. 

Thanks for any kind of help

**Comment by lah7** [comment]
Hi there. I have updated the packaging, so that Ubuntu 14.04 and Linux Mint 17 are supported.

If you have added the PPA, an update will come through:

    sudo add-apt-repository ppa:lah7/polychromatic
    sudo apt update
    sudo apt install polychromatic

[A stand alone package is also available](https://github.com/lah7/polychromatic/releases/download/v0.2.0/polychromatic_0.2.0_trusty_and_wily_all.deb), but I recommend the PPA as this keeps the application up-to-date.

----------
#### Technical Reasons
Linux Mint 17 is based on Ubuntu 14.04 "Trusty", so the dependency (`gir1.2-webkit2-4.0`) isn't available -- only 16.04 "Xenial" and newer. 

However, I have just discovered the older version (`gir1.2-webkit2-3.0`) is available for 14.04+, and have updated the packaging so these versions are supported.

Linux Mint 18 is based on 16.04 "Xenial", so this won't be a problem in future versions.

-----------
Let me know if it works. :+1:

**Comment by innoce9t** [comment]
Hey, So I just tried installing it using the PPA and the good news it is successfully installed, However i still cant run it. 
I tried reinstalling it and still doesnt run, no GUI shows up.

**Comment by lah7** [comment]
Please run it in a terminal and paste the output here, this'll show some error details.

    polychromatic-controller

**Comment by innoce9t** [comment]
yes sorry about that. It appears to be some problem in webkit.
`innoce9t@Asus ~ $ polychromatic-controller
Loading preferences from "/home/innoce9t/.config/polychromatic/preferences.json'...
Successfully loaded preferences.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 798, in <module>
    app = Controller()
  File "/usr/bin/polychromatic-controller", line 136, in __init__
    self.webkit = AppView()
  File "/usr/bin/polychromatic-controller", line 50, in __init__
    self.get_settings().set_property('allow-file-access-from-file-urls', 1)
TypeError: object of type `WebKitSettings' does not have property `allow-file-access-from-file-urls'
innoce9t@Asus ~ $ Error receiving IPC message on socket -1 in process 21508: Bad file descriptor
`

**Comment by lah7** [comment]
I see... WebKit2 is giving me a nightmare with these subtle differences in its API (hence the error) :confounded:  Instead, I decided to revert back to `v0.1.0` (based on WebKit 1) for Ubuntu 14.04, 15.10 and LM 17.

A new update (`0.2.0.1`) is on its way in the PPA [(or manually here)](https://github.com/lah7/polychromatic/releases/download/v0.2.0/polychromatic_0.1.0_trusty_wily_all.deb). Being based on the earlier version this one should be good to go.

**Comment by innoce9t** [comment]
I am sorry to hear that but never the less I really appreciate your dedication and hard work... I would like to help out if in anyway i can . Thanks alot 
Looking forward to the upcoming update

**Comment by lah7** [comment]
Polychromatic `v0.1.0` and `v0.2.0` offer the same functionality, it's just that under the hood it's powered by different WebKit APIs. Their documentation can be a bit confusing too.

I presume things are working, if not, feel free to comment on this issue again.
