### ISSUE TITLE
WebKitSettings error : can't launch the app

### ISSUE THREAD

**Issue by Geospace** [lah7/polychromatic#17]
Hey ! :-D

I'm running a fresh install of Debian 8 (x64) and I use a Razer Chroma Blackwidow Ultimate. I installed the driver, the latest stable .deb available and all its dependencies (with `apt-get -f install`). When I try to run the application, here is what I get : 

```
$ ./polychromatic-controller 
Using "/usr/share/locale/" for translations.
Loading preferences from "/home/geographer/.config/polychromatic/preferences.json'...
Successfully loaded preferences.
Traceback (most recent call last):
  File "./polychromatic-controller", line 817, in <module>
    app = Controller()
  File "./polychromatic-controller", line 154, in __init__
    self.webkit = AppView()
  File "./polychromatic-controller", line 68, in __init__
    self.get_settings().set_property('allow-file-access-from-file-urls', 1)
TypeError: object of type `WebKitSettings' does not have property `allow-file-access-from-file-urls'
$ Error receiving IPC message on socket -1 in process 13828: Bad file descriptor
```

Did I miss something ? Thank's for your help ! :-)

**Comment by lah7** [comment]
Hi there.  Polychromatic requires `gir1.2-webkit2-4.0` [(available in jessie-backports)](https://packages.debian.org/jessie-backports/s390x/introspection/gir1.2-webkit2-4.0), and this error is likely because it's using `gir1.2-webkit2-3.0` instead.

I presume this running directly from the repository. Check that `gir1.2-webkit2-4.0` is definitely installed.

Alternatively, there is a package available: [polychromatic_0.2.0_all.deb](https://github.com/lah7/polychromatic/releases/download/v0.2.0/polychromatic_0.2.0_all.deb)

**Comment by Geospace** [comment]
Actually both versions were installed. Maybe they are conflincting each others ?

By the way, the deb link is dead (that's also the case in the README) so I downloaded it from [here](https://github.com/lah7/polychromatic/releases/tag/v0.2.0).

Anyway, I download the 0.1.0 version which uses the correct Webkit version for my system and everything works great... 

Thank you for your help ! :-D

**Comment by lah7** [comment]
It would be odd if they conflict, since Python specifically asks for version 4.0.

Thanks for pointing out the dead link, my bad for renaming files! Fixed.

`v0.1.0` is based on the older WebKit, but glad to hear it's working. :+1:
