### ISSUE TITLE
Add support for the OpenRazer driver

### ISSUE THREAD

**Issue by m4ng0squ4sh** [lah7/polychromatic#21]
I would love to see official support for the [OpenRazer driver](https://github.com/openrazer/razer-drivers). This is a complete rewrite of the razer_chroma_driver fixing several issues (code cleanup, busy wait, USB request confirmation, mutex locks, detailed error messages,...).

There is a [small script](https://github.com/openrazer/razer-drivers/tree/master/scripts) helping to setup custom key colors. This might be an inspiration for future support of custom key color profiles for polychromatic :+1: 

If you miss some functionalities or specific device support, please let me know!

**Comment by lah7** [comment]
Thanks for sharing. I like the cleanup efforts and "OpenRazer" sounds like a really good name (instead of _**razer-drivers**_ or _**Linux Chroma Drivers**_ or _**razer-chroma-drivers**_, not even sure myself). OpenRazer fits nicely. :+1: 

At the moment, there isn't a programming interface in the OpenRazer repository so Polychromatic cannot easily interface with this driver at the moment. Please do consider creating one, take a look at [**pylib** from the original repository](https://github.com/pez2001/razer_chroma_drivers/tree/master/pylib)  to see how the current driver users DBus to interact with the driver.

It is possible to use plain old commands executed by root (or create a sudoers to bypass the prompt) but I'd really avoid that approach.

[v0.3.0](https://github.com/lah7/polychromatic/milestone/2) intends to be compatible with @terrycain's new daemon,, so the future intends to restructure the program so it properly supports multiple devices and could potentially support multiple drivers.

I fear efforts may be duplicated though as there are now 3 drivers achieving the same purpose:

* [razer_chroma_drivers](https://github.com/pez2001/razer_chroma_drivers) - Original repo. Primary.
  * [razer_drivers](https://github.com/terrycain/razer_drivers) - Active fork and **Daemonv2**.
* [OpenRazer](https://github.com/openrazer/razer-drivers) - Re-wriiten.

**Comment by m4ng0squ4sh** [comment]
Thanks for the fast response! I am planing to create a daemon with a command line tool called **razerctl**. The daemon is programmed with the Go programming language, it supports multiple devices and it is almost ready. I'll publish it soon on GitHub.

Right now I have to make the decision to choose the daemon communication type:
- DBUS
- [PAKT](https://github.com/desertbit/pakt)

I prefer PAKT, but right now there is no Python support. However a Python PAKT client can be added. As alternative you could make use of the command line tool, calling it directly without root privileges from your application (Similar to systemctl).

Example:
```
$ razerctl devices
$ razerctl set-mode wave
$ razerctl set-mode spectrum
```

I am open for ideas and you're welcome to join the OpenRazer project :-)

> I fear efforts may be duplicated though as there are now 3 drivers achieving the same purpose:

The original razer_chroma_drivers project is dead. pez2001 does not respond to any e-mails and does not include any pull requests.

There is an active fork of the razer_chroma_drivers project mainly managed by terrycain. I had a chat with Terry Cain and Gabriele Musco (Author of razerCommander). I informed them about the bad shape of the kernel driver source code and suggested to create a new organization, split the driver source and the daemon into separate repositories and include some of the GUI applications. I would mainly cleanup and manage the driver, the others would be responsible for the daemon and the GUI applications. However Terry was not interested. Allegedly because his git history would have got lost (This would be solvable).

So, I didn't have any choice. I can't add any new device support to an existing project, if the source code is a huge mess. I would love to see this driver in the Linux mainline kernel and I'll propose it soon. The current source code is in a good shape and there is a good chance to get this included :-)

**Comment by lah7** [comment]
I have decided Polychromatic should stick to **one daemon** and do the job well for the short to medium term, especially as [the original driver has released a brand new daemon and Python library](https://github.com/terrycain/razer-drivers/releases/tag/v1.0.0).

Features (like application profiles) are also tied to this daemon, which makes it inconvenient to support multiple **daemons** right now.

-----------
I do feel efforts have been duplicated, and will potentially lead to confusion later as your OpenRazer project has nicked the same logo _(and desired name...)_ :disappointed:

**Comment by m4ng0squ4sh** [comment]
I would love to join all our efforts into one single project. But this was initially not possible, due to different opinions about code quality. However, now during the first stable kernel release, I hope we can get things sorted out and merge our efforts :) If that's not possible or Terry is not interested, I am open to rename my project and use a different logo, if requested.

However, please have a look at our initial [daemon client library implementation.](https://github.com/openrazer/openrazer/blob/master/samples/python/main.py) Even, if you're not going to use it...

**Comment by lah7** [comment]
A new release of Polychromatic is imminent, which will continue to use the [razer-drivers daemon](https://github.com/terrycain/razer-drivers) as it works well with this program and is pretty stable (even if driver code quality has been debated).

I won't rule out support for other daemons, but it seems like something for the long term. Like I say, I fear efforts are duplicated.

----------
As feedback, I prefer @terrycain's implementation of having devices as objects, as opposed to passing a string containing the serial number.

```
import razer.client
a = razer.client.DeviceManager()
```

As opposed to your driver's draft:

```

```
