### ISSUE TITLE
No devices found/tray applet non-functional

### ISSUE THREAD

**Issue by ashfallen0** [lah7/polychromatic#37]
installed razer drivers(razer-chroma-driver_20160612_ubuntu_amd64.deb), this PPA, apt update, apt install polychromatic

Devices:
2013 Razer BlackWidow Keyboard (shows all support in reference)
2013 Razer Naga mouse (No support shown in reference)

lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial

Relevant lsusb:
Bus 003 Device 004: ID 1532:0015 Razer USA, Ltd Naga Mouse
Bus 003 Device 002: ID 1532:010d Razer USA, Ltd

$ polychromatic-controller 
--app launches, then displays yellow (?)
"Please check your Razer device is connected and that the daemon supports your device, then try again."

$ polychromatic-tray-applet 
Using "/usr/share/locale/" or falling back to "en_US" for translations.
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 625, in <module>
    indicator = AppIndicator()
  File "/usr/bin/polychromatic-tray-applet", line 182, in **init**
    self.active_device = devlist[0]
IndexError: list index out of range

**Comment by lah7** [comment]
> razer-chroma-driver_20160612_ubuntu_amd64.deb

That package would install the old driver/daemon. Just to clarify, the packages should come from @terrycain's PPA: [`terrz/razerutils`](https://github.com/lah7/polychromatic#driver-installation). I'm suspecting they are installed as you see a yellow warning "No Devices Found" when opening the Controller app.

-----------
It seems this is no fault of Polychromatic, everything is installed correctly. It's because (unluckily) neither of these devices are supported by the daemon yet.

* The **Razer Naga** mouse [has an open issue here](https://github.com/terrycain/razer-drivers/issues/59) requesting support.
* Your **BlackWidow Chroma** Keyboard is actually a 2012 model (with USB ID `1532:010d`). This has driver support, but not for the daemon. [You should open an issue requesting daemon support on the driver's repository.](https://github.com/terrycain/razer-drivers/issues/new)

Once these devices are supported by the daemon, they'll work in Polychromatic.

-----
I'll consider adding a feature to "detect" other Razer devices (USB VID `1532`) if none were found, indicating missing driver/daemon support.

**Comment by ashfallen0** [comment]
Yeah, swapping drivers didn't resolve the problem, still the yellow (?).

I'm opening a support request on the other page.  Thank you for catching the USB id code to the 2012 model. That solves some hair pulling.

Thank you for the quick support reply!

**Comment by terrycain** [comment]
> I'll consider adding a feature to "detect" other Razer devices (USB VID 1532) if none were found, indicating missing driver/daemon support.

Am also thinking of adding that to the dameon :wink:

**Comment by z3ntu** [comment]
@ashfallen0 Are you sure, that `1532:0015` is a **2013** Razer Naga? 1. There is no 2013 Razer Naga. 2. The `0x0015` Naga was released in 2009 and is the "Razer Naga Classic".
