### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by OldMike** [lah7/polychromatic#48]
Hi,

I'm using Archlinux and installed the driver package (https://terrycain.github.io/razer-drivers/#arch). But Im running webkitgtk 2.4.11.3 so I guess this is why I can't have my Razor kb properly running on my Arch.
I won't downgrade due to dependencies, do you plan on upgrading your app please?

Thanks a lot!

**Comment by lah7** [comment]
[There's currently a known bug with WebKit2](https://bugs.webkit.org/show_bug.cgi?id=165073), which should be fixed in their next release (2.14.3 and the latest trunk). There was a warning in the README *(now removed)* as a workaround was recently added.

There's no need to downgrade WebKit2 anymore, the app should work fine with the latest version of WebKitGTK. Please confirm if the app works for you?

--------
Although, @z3ntu **(in charge of packaging for Arch)** has [commented `webkitgtk` is not installed for him yet still works](https://github.com/lah7/polychromatic/issues/39#issuecomment-270343522), so there is likely a different dependency for WebKitGTK in use. :confused:

**Comment by z3ntu** [comment]
`webkit2gtk` is now a dependency in the Arch package; sorry for the inconvenience

**Comment by OldMike** [comment]
I plugged my BW Chroma and reinstalled the drivers/Polychromatic many times, but I'm still out of the game.
http://pix.toile-libre.org/upload/original/1484586440.png

**Comment by z3ntu** [comment]
Please post the output of
`ls -lah /sys/bus/hid/drivers/razerkbd/`

**Comment by lah7** [comment]
FYI, this is not a WebKitGTK or Polychromatic bug, but rather likely the daemon does not support your device (or specific model), so it will not show up here.

**Comment by OldMike** [comment]
Well, I have nothing here:
```
┬─[mika@mika:/sys/bus/hid/drivers]─[11:51:24]
╰─>$ ls -lah /sys/bus/hid/drivers/
total 0
drwxr-xr-x 3 root root 0 17 janv. 11:55 ./
drwxr-xr-x 4 root root 0 16 janv. 18:04 ../
drwxr-xr-x 2 root root 0 16 janv. 18:04 hid-generic/
```

Here are my installed packages:
```
┬─[mike@mika:~]─[11:52:03]
╰─>$ yaourt -Qs razer
local/polychromatic 0.3.6-2
    A graphical front end for managing Razer peripherals under GNU/Linux.
local/python-razer 1.1.5-2
    A python library for controlling razer-daemon
local/razer-daemon 1.1.5-2
    A daemon for controlling razer-driver
local/razer-driver-dkms 1.1.5-1
    An entirely open source driver for managing Razer peripherals on Linux. 
    (DKMS)
local/razer-driver-meta 1.1.2-1
    Meta package for razer-driver. Provides DKMS module, daemon and python 
    library

```

**Comment by z3ntu** [comment]
Update to the newest version (`1.1.6`) for `razer-driver-dkms`, `razer-daemon` & `python-razer`, then reboot and try again. Also please post the output of `lsusb | grep -i razer`.

**Comment by OldMike** [comment]
I don't know why/how but after update/reboot it works!  Thanks a lot :)
