### ISSUE TITLE
Icons on the top right corner get triggered twice

### ISSUE THREAD

**Issue by claell** [lah7/polychromatic#56]
When clicking on the folder icon or github logo the action will performed twice, resulting in two opened folders or webpages.

**Comment by lah7** [comment]
This is a tricky one, it's a bug in WebKit2 which has been fixed in their latest version(s). I did commit a workaround here, but it has since been removed it as it would introduce new problems later.

The solution is to wait for your distro to update the WebKit2 library. This should come within the next week or two as a security update.

**Comment by claell** [comment]
Alright, then I will just wait a bit.

**Comment by claell** [comment]
I can confirm this is no longer happening for me!
