### ISSUE TITLE
DPI adjustment slider is glitchy

### ISSUE THREAD

**Issue by aaronkmiller** [lah7/polychromatic#65]
Polychromatic Version 0.3.7
Hardware: Razer Ouroboros

When adjusting the brightness slider, the DPI slider and numeric display starts bouncing around on its own, oscillating between its current value and 0 or 256. Actual hardware performance isn't affected. I've also seen this happen when interacting with other elements on the page but not as consistently.

**Comment by lah7** [comment]
For the DPI slider, there's a typo in the driver (fixed in https://github.com/terrycain/razer-drivers/commit/1b684bc291aaf6fe2632855bdc215ad253fecf6f) but I'm not sure if a new driver version has been released yet with this fix.

Polychromatic tries to keep the slider in "sync" with the hardware, but this typo (1600 instead of 16000) causes the slider to stay capped to that position.

**Comment by z3ntu** [comment]
That commit doesn't change any behavior in Polychromatic (as I already told you 😉).

**Comment by lah7** [comment]
@z3ntu If we're talking about the slider being capped ("bouncing back") to `1600`, that commit definitely fixes that.

![peek 2017-03-14 18-41](https://cloud.githubusercontent.com/assets/13032135/23916996/dea28888-08e5-11e7-807a-022c24e59249.gif)

But I guess as I look again, this issue is referring to this quirk -- while dragging:

![peek 2017-03-14 18-42](https://cloud.githubusercontent.com/assets/13032135/23917058/10dbb766-08e6-11e7-90a4-452f2474f3ba.gif)

If that's the issue, the solution here is to remove this "sync" so pressing hardware buttons won't reflect the value on screen. If @terrycain added a signal to catch when the hardware DPI button is pressed (if possible), even better!

**Comment by z3ntu** [comment]
I just saw it going to 0 for about half a second when just clicking and not dragging the slider.

**Comment by AaronM-Cloudtek** [comment]
It's very erratic

![peek 2017-03-14 13-19](https://cloud.githubusercontent.com/assets/11548856/23920760/2ab5b114-08b9-11e7-816c-6e1e5f9db662.gif)

**Comment by aaronkmiller** [comment]
It's very erratic

![peek 2017-03-14 13-19](https://cloud.githubusercontent.com/assets/679603/23920828/7415ade6-08b9-11e7-939b-0ad00207e36b.gif)

**Comment by lah7** [comment]
Quite odd behaviour -- the daemon may be strained, since after making any change, it gets the value back from the daemon again... and it seems it disagrees with what it was set in the UI.

For now, I'll take out the "sync" thing that's going on in the background.

----------
For the brightness, what happens to your mouse when setting it from 0-100%? Do the lights change?

*[(By the way, you'll see images for your device on the next daemon update)](https://github.com/terrycain/razer-drivers/commit/80c9e6009f0de0f2fcfcf489adaa4ab519d9ee0d)*

**Comment by aaronkmiller** [comment]
Yes when adjusting the slider the lights on my mouse change, although when set to "Off" they are still on just dimmed.

Also I just noticed if I leave the tab and come back the correct brightness value is displayed.

> (By the way, you'll see images for your device on the next daemon update)

I'm seeing that image already actually! Snazzy :)
