### ISSUE TITLE
The app icon isn't noticeable on light themes

### ISSUE THREAD

**Issue by aldy-art** [lah7/polychromatic#66]
This is how looks the app icon right now on a light theme. (That is the default theme on Plasma KDE)
![app-menu-original](https://cloud.githubusercontent.com/assets/1350839/23782668/d454fdd4-0534-11e7-9d64-481841096123.png)
As you can see the icon isn't very noticeable.

I did some modifications to the icon to look like this:
![app-icon](https://cloud.githubusercontent.com/assets/1350839/23782704/1cfcff50-0535-11e7-91ff-fc9674fc21e5.png)

So, this is how looks with the new icon on the app launcher. I think that is more visible now.
![app-menu-new-light](https://cloud.githubusercontent.com/assets/1350839/23782716/343d0354-0535-11e7-9824-ef5f67a132c9.png)

And it works on dark themes too:
![app-menu-new-dark](https://cloud.githubusercontent.com/assets/1350839/23782728/44c7cc9a-0535-11e7-9b8e-407ffc2d4204.png)

Download svg icon: [app-icon.zip](https://github.com/lah7/polychromatic/files/833019/app-icon.zip)

**Comment by lah7** [comment]
Thanks for sharing -- I like the squarer keyboard keys and the subtle gradient at the back. :+1: 

The only thing I'd change is the multi-colour outline with a solid green, as it looks less dazzling and less like the [razer-drivers "Chroma" logo](https://github.com/terrycain/razer-drivers/tree/master/logo).

![image](https://cloud.githubusercontent.com/assets/13032135/23798537/06395184-059d-11e7-9a33-91dae9ae3e49.png)
![image](https://cloud.githubusercontent.com/assets/13032135/23798543/0ec11530-059d-11e7-85cb-f9fa2c7f2e67.png)

:point_up: Is there also an entry for Polychromatic Controller too?

---------
My only gripe with putting it in a circle (which it was originally) is that the logo looks tiny on the MATE Desktop:

![image](https://cloud.githubusercontent.com/assets/13032135/23798642/7735992e-059d-11e7-9937-e62355e75b26.png) ![image](https://cloud.githubusercontent.com/assets/13032135/23798632/6bdcbb5c-059d-11e7-9875-a8f37ea8fff6.png)

But it should be possible to have different versions at various sizes, so that satisfies different menus (ish -- still a problem on lighter backgrounds). :smile: 

![image](https://cloud.githubusercontent.com/assets/13032135/23798999/e13f46ac-059e-11e7-8228-99ceb9976f8e.png)

**Comment by aldy-art** [comment]
Tell me if you like some of this versions.

Tray icon:
![app-tray-icon-v1](https://cloud.githubusercontent.com/assets/1350839/23821260/60e76a58-060b-11e7-9f30-5df03cc333a2.png) ![app-tray-icon-v2](https://cloud.githubusercontent.com/assets/1350839/23821261/63dc1dbc-060b-11e7-9f9e-a3e939bf9328.png)

Controller icon:
![app-controller-icon-v1](https://cloud.githubusercontent.com/assets/1350839/23821264/78b6e5e6-060b-11e7-97c6-ead6eb45604b.png) ![app-controller-icon-v2](https://cloud.githubusercontent.com/assets/1350839/23821265/78c048fc-060b-11e7-8d76-87f04426364a.png)
![app-controller-icon-v3](https://cloud.githubusercontent.com/assets/1350839/23821266/78cad506-060b-11e7-8dec-f37c7851ce0e.png) ![app-controller-icon-v4](https://cloud.githubusercontent.com/assets/1350839/23821267/78d52e02-060b-11e7-87cb-2cc39a1b4bad.png)

What do you think?

**Comment by aldy-art** [comment]
I forgot to add the svg icons.

[icon-variants.zip](https://github.com/lah7/polychromatic/files/835565/icon-variants.zip)

**Comment by lah7** [comment]
Thanks again -- I prefer the square outline, and the idea of having different icons for the tray and controller. I'll go ahead and add your proposed green versions of the tray icon and the "slider" version for the Controller.

I like the cog too, but I think the slider better represents customisation and choice, whereas cogs is more towards system and "fixed" settings that won't change much.
