### ISSUE TITLE
Razer Blade 2016

### ISSUE THREAD

**Issue by tomrozb** [lah7/polychromatic#71]
I've tried to install it on Mint 18.1 and it doesn't seem to work with Razer Blade 2016. Is this laptop even supported?

**Comment by lah7** [comment]
Doesn't look like it - not yet anyway - please see this issue here: https://github.com/terrycain/razer-drivers/issues/214

This is assuming that your device is a `1532:0224` when you type this into a terminal:

    lsusb | grep 'Razer'

There's nothing Polychromatic can do here. Once the driver/daemon is supported, this application will work too.

**Comment by tomrozb** [comment]
Mine is early 2016, `lsusb` output below

`Bus 001 Device 004: ID 1532:020f Razer USA, Ltd `
